import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Home,ClipboardList,Settings,Search,Plus,Minus,Trash2,ChevronLeft,Save,ChefHat,Menu as MenuIcon,UtensilsCrossed,Pizza,Languages,X,CheckCircle,LayoutGrid}from"lucide-react";import"./style.css";
const cats=["بيتزا","سندويتشات","أطباق رئيسية","مشروبات","حلويات"];
const catFr={"بيتزا":"Pizzas","سندويتشات":"Sandwichs","أطباق رئيسية":"Plats principaux","مشروبات":"Boissons","حلويات":"Desserts"};
const initial=[['Margherita Pizza','بيتزا مارغريتا','Pizza Margherita',900,'بيتزا','🍕'],['Cheeseburger','تشيز برغر','Cheeseburger',800,'سندويتشات','🍔'],['Grilled Steak','ستيك مشوي','Steak grillé',2200,'أطباق رئيسية','🥩'],['Pasta Alfredo','باستا ألفريدو','Pâtes Alfredo',1200,'أطباق رئيسية','🍝'],['Caesar Salad','سلطة سيزر','Salade César',700,'أطباق رئيسية','🥗'],['Tiramisu','تيراميسو','Tiramisu',600,'حلويات','🍰'],['Coca Cola','كوكا كولا','Coca-Cola',300,'مشروبات','🥤']].map((x,i)=>({id:i+1,name:x[0],ar:x[1],fr:x[2],price:x[3],cat:x[4],emoji:x[5]}));
const money=n=>n.toLocaleString('fr-DZ')+' DA';
const labels={ar:{start:'بدء الاستخدام',tables:'الطاولات',orders:'الطلبات',settings:'الإعدادات',choose:'اختر الطاولة',table:'الطاولة',search:'ابحث عن وجبة...',all:'الكل',cart:'عرض الطلب',save:'حفظ الطلب',total:'المجموع',saved:'الطلبات المحفوظة',admin:'لوحة التحكم',meals:'الوجبات',categories:'التصنيفات',tableCount:'الطاولات',addMeal:'إضافة وجبة',editMeal:'تعديل الوجبة',custom:'تخصيص الطلب',confirm:'إضافة للطلب',cancel:'إلغاء',notes:'ملاحظات خاصة',options:'خيارات الوجبة',language:'Français',empty:'السلة فارغة',closeTable:'إنهاء الطلب وتحرير الطاولة',done:'تم إنهاء الطلب',emptyTables:'فارغة',busy:'مشغولة',delete:'حذف',edit:'تعديل',saveChanges:'حفظ التعديلات'},fr:{start:'Commencer',tables:'Tables',orders:'Commandes',settings:'Réglages',choose:'Choisir une table',table:'Table',search:'Rechercher un plat...',all:'Tout',cart:'Voir la commande',save:'Enregistrer la commande',total:'Total',saved:'Commandes enregistrées',admin:'Tableau de bord',meals:'Plats',categories:'Catégories',tableCount:'Tables',addMeal:'Ajouter un plat',editMeal:'Modifier le plat',custom:'Personnaliser la commande',confirm:'Ajouter à la commande',cancel:'Annuler',notes:'Notes spéciales',options:'Options du plat',language:'العربية',empty:'Le panier est vide',closeTable:'Terminer la commande et libérer la table',done:'Commande terminée',emptyTables:'Libre',busy:'Occupée',delete:'Supprimer',edit:'Modifier',saveChanges:'Enregistrer les modifications'}};
const defaultMods={pizza:[['Cuisson','Normale','Bien cuite']],burger:[['Cuisson','À point','Bien cuite'],['Oignons','Avec oignons','Sans oignons'],['Sauce','Classique','Sans sauce']],steak:[['Cuisson','Saignant','À point','Bien cuit']],pasta:[['Sauce','Normale','Sauce légère'],['Fromage','Avec fromage','Sans fromage']],salad:[['Sauce','À part','Normale'],['Oignons','Avec oignons','Sans oignons']],drink:[['Glace','Avec glace','Sans glace']],dessert:[['Chantilly','Avec','Sans']]};
function getMods(x){if(x.cat==='بيتزا')return defaultMods.pizza;if(x.name.includes('Burger'))return defaultMods.burger;if(x.name.includes('Steak'))return defaultMods.steak;if(x.name.includes('Pasta'))return defaultMods.pasta;if(x.name.includes('Salad'))return defaultMods.salad;if(x.cat==='مشروبات')return defaultMods.drink;if(x.cat==='حلويات')return defaultMods.dessert;return[]}
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
function App(){const[screen,setScreen]=useState('welcome'),[lang,setLang]=useState(localStorage.getItem('bistro_lang')||'ar'),[table,setTable]=useState(),[cart,setCart]=useState([]),[items,setItems]=useState(()=>load('bistro_items',initial)),[filter,setFilter]=useState('الكل'),[search,setSearch]=useState(''),[orders,setOrders]=useState(()=>load('bistro_orders',[])),[admin,setAdmin]=useState('main'),[custom,setCustom]=useState(null),[chosen,setChosen]=useState({}),[notes,setNotes]=useState(''),[edit,setEdit]=useState(null);
useEffect(()=>localStorage.setItem('bistro_items',JSON.stringify(items)),[items]);useEffect(()=>localStorage.setItem('bistro_orders',JSON.stringify(orders)),[orders]);useEffect(()=>localStorage.setItem('bistro_lang',lang),[lang]);
const t=labels[lang],dir=lang==='ar'?'rtl':'ltr';const shown=useMemo(()=>items.filter(x=>(filter==='الكل'||x.cat===filter)&&(x.name.toLowerCase().includes(search.toLowerCase())||x.ar.includes(search)||x.fr.toLowerCase().includes(search.toLowerCase()))),[items,filter,search]);const total=cart.reduce((s,x)=>s+x.price*x.qty,0);const busyTables=new Set(orders.map(o=>o.table));
const addItem=(x,mods={},note='')=>{setCart(c=>[...c,{...x,key:Date.now()+Math.random(),qty:1,mods,note}]);setCustom(null);setChosen({});setNotes('')};const change=(key,d)=>setCart(c=>c.map(i=>i.key===key?{...i,qty:Math.max(1,i.qty+d)}:i));const toggleLang=()=>setLang(lang==='ar'?'fr':'ar');
function Header({back}){return <header><button onClick={()=>back?setScreen(back):setScreen('tables')}>{back?'‹':<MenuIcon/>}</button><div><b>THE BISTRO</b><small>RESTAURANT</small></div><button onClick={toggleLang}><Languages/></button></header>};function Nav(){return <nav><button onClick={()=>setScreen('tables')}><Home/>{t.tables}</button><button onClick={()=>setScreen('orders')}><ClipboardList/>{t.orders}</button><button onClick={()=>{setAdmin('main');setScreen('admin')}}><Settings/>{t.settings}</button></nav>}
if(screen==='welcome')return <div className="app welcome" dir={dir}><ChefHat size={82}/><h1>THE BISTRO</h1><small>RESTAURANT</small><p>Good Food • Good Mood</p><div className="lang"><button className={lang==='ar'?'sel':''} onClick={()=>setLang('ar')}>العربية</button><button className={lang==='fr'?'sel':''} onClick={()=>setLang('fr')}>Français</button></div><button className="start" onClick={()=>setScreen('tables')}>{t.start}<ChevronLeft/></button></div>;
if(screen==='tables')return <div className="app" dir={dir}><Header/><main><h2>{t.choose}</h2><div className="tables">{Array.from({length:25},(_,i)=>i+1).map(n=><button className={'table '+(busyTables.has(n)?'busy':'')} onClick={()=>{setTable(n);setCart([]);setFilter('الكل');setSearch('');setScreen('menu')}} key={n}>{n}<span>{busyTables.has(n)?'🔴':'🟢'}</span></button>)}</div><div className="legend">🟢 {t.emptyTables}　 🔴 {t.busy}</div></main><Nav/></div>;
if(screen==='menu')return <div className="app" dir={dir}><Header back="tables"/><h2>{t.table} {table}</h2><main><div className="search"><Search/><input placeholder={t.search} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="chips">{[t.all,...cats].map(c=><button key={c} className={(filter==='الكل'&&c===t.all)||filter===c?'active':''} onClick={()=>setFilter(c===t.all?'الكل':c)}>{c===t.all?c:(lang==='fr'?catFr[c]:c)}</button>)}</div>{shown.map(x=><div className="food" key={x.id} onClick={()=>{setCustom(x);setChosen({});setNotes('')}}><span className="emoji">{x.emoji}</span><div className="info"><b>{lang==='fr'?x.fr:x.name}</b><small>{lang==='fr'?x.name:x.ar}</small><strong>{money(x.price)}</strong></div><button className="plus" onClick={e=>{e.stopPropagation();setCustom(x);setChosen({});setNotes('')}}>+</button></div>)}<button className="save" onClick={()=>setScreen('cart')}>{t.cart} ({cart.reduce((s,x)=>s+x.qty,0)})</button></main>{custom&&<Customizer item={custom}/>}</div>;
function Customizer({item}){const mods=getMods(item);return <div className="modal"><div className="box" dir={dir}><div className="modalHead"><h3>{t.custom}</h3><button onClick={()=>setCustom(null)}><X/></button></div><div className="selectedFood"><span>{item.emoji}</span><div><b>{lang==='fr'?item.fr:item.name}</b><small>{money(item.price)}</small></div></div><h4>{t.options}</h4>{mods.map((m,idx)=><div className="mod" key={idx}><b>{m[0]}</b><div className="modBtns">{m.slice(1).map(v=><button key={v} className={chosen[idx]===v?'selected':''} onClick={()=>setChosen({...chosen,[idx]:v})}>{v}</button>)}</div></div>)}<label>{t.notes}</label><textarea placeholder={lang==='fr'?'Ex: allergie, sauce à part, sans sel...':'مثال: حساسية، الصوص على الجانب، بدون ملح...'} value={notes} onChange={e=>setNotes(e.target.value)}/><div className="modalActions"><button onClick={()=>setCustom(null)}>{t.cancel}</button><button className="save" onClick={()=>addItem(item,chosen,notes)}>{t.confirm}</button></div></div></div>}
if(screen==='cart')return <div className="app" dir={dir}><Header back="menu"/><h2>{t.table} {table}</h2><main>{cart.length===0?<div className="center"><p>{t.empty}</p><button className="save" onClick={()=>setScreen('menu')}>{t.tables==='Tables'?'Ajouter des plats':'إضافة وجبات'}</button></div>:<>{cart.map(x=><div className="cart" key={x.key}><span className="emoji">{x.emoji}</span><div className="info"><b>{lang==='fr'?x.fr:x.name}</b><small>{Object.values(x.mods||{}).join(' · ')}{x.note&&' · '+x.note}</small><strong>{money(x.price*x.qty)}</strong></div><div className="qty"><button onClick={()=>change(x.key,-1)}><Minus/></button>{x.qty}<button onClick={()=>change(x.key,1)}><Plus/></button></div><button className="del" onClick={()=>setCart(c=>c.filter(i=>i.key!==x.key))}><Trash2/></button></div>)}<div className="total"><b>{t.total}</b><strong>{money(total)}</strong></div><button className="save" onClick={()=>{if(!cart.length)return;setOrders(o=>[{id:Date.now(),table,items:cart,total,time:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),status:'open'},...o]);setCart([]);setScreen('orders')}}><Save/>{t.save}</button></>}</main></div>;
if(screen==='orders')return <div className="app" dir={dir}><Header/><h2>{t.saved}</h2><main>{orders.length===0?<div className="center"><p>{t.empty}</p></div>:orders.map(o=><div className="order" key={o.id}><b>{t.table} {o.table}</b><small>{o.items.reduce((s,x)=>s+x.qty,0)} {lang==='ar'?'وجبة/عنصر':'articles'}　{o.time}</small><strong>{money(o.total)}</strong><button className="save" onClick={()=>setOrders(os=>os.map(v=>v.id===o.id?{...v,status:'closed'}:v))}>{o.status==='closed'?<><CheckCircle/> {t.done}</>:t.closeTable}</button></div>)}</main><Nav/></div>;
if(admin==='main')return <div className="app admin" dir={dir}><Header/><h2>{t.admin}</h2><main>{[[UtensilsCrossed,t.meals,'','meals'],[LayoutGrid,t.categories,'','cats'],[Pizza,t.tableCount,'25 '+(lang==='ar'?'طاولة':'tables'),'tables']].map(([I,a,b,v])=><button key={v} className="adminCard" onClick={()=>setAdmin(v)}><I/><div><b>{a}</b><small>{b||a}</small></div><ChevronLeft/></button>)}</main><Nav/></div>;
return <div className="app admin" dir={dir}><Header/><h2>{admin==='meals'?t.meals:admin==='cats'?t.categories:t.tableCount}</h2><main>{admin==='meals'&&<><button className="save" onClick={()=>setEdit({new:true})}>{t.addMeal} ＋</button>{items.map(x=><div className="adminMeal" key={x.id}><span>{x.emoji}</span><div><b>{lang==='fr'?x.fr:x.name}</b><small>{x.fr} · {money(x.price)}</small></div><button onClick={()=>setEdit(x)}>{t.edit}</button><button onClick={()=>setItems(is=>is.filter(i=>i.id!==x.id))}><Trash2/></button></div>)}</>}{admin==='cats'&&cats.map(c=><div className="adminMeal" key={c}><b>{lang==='fr'?catFr[c]:c}</b><small>{items.filter(x=>x.cat===c).length} {lang==='fr'?'plats':'وجبات'}</small></div>)}{admin==='tables'&&<div className="center"><h3>25 {lang==='ar'?'طاولة':'tables'}</h3><p>{lang==='ar'?'عدد الطاولات ثابت في هذه النسخة.':'Le nombre de tables est fixé à 25 dans cette version.'}</p></div>}</main>{edit&&<MealEditor value={edit} close={()=>setEdit(null)}/>}</div>;
function MealEditor({value,close}){const isNew=value.new;const [form,setForm]=useState(isNew?{name:'',ar:'',fr:'',price:'',cat:cats[0],emoji:'🍽️'}:{name:value.name,ar:value.ar,fr:value.fr,price:value.price,cat:value.cat,emoji:value.emoji});const set=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=e=>{e.preventDefault();const x={...form,id:isNew?Date.now():value.id,price:Number(form.price)};setItems(is=>isNew?[...is,x]:is.map(i=>i.id===x.id?x:i));close()};return <div className="modal"><form className="box" onSubmit={submit}><div className="modalHead"><h3>{isNew?t.addMeal:t.editMeal}</h3><button type="button" onClick={close}><X/></button></div><input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Nom / اسم الوجبة" required/><input value={form.ar} onChange={e=>set('ar',e.target.value)} placeholder="العربية"/><input value={form.fr} onChange={e=>set('fr',e.target.value)} placeholder="Français"/><input value={form.price} onChange={e=>set('price',e.target.value)} type="number" min="0" placeholder="Prix / السعر DA" required/><select value={form.cat} onChange={e=>set('cat',e.target.value)}>{cats.map(c=><option key={c} value={c}>{lang==='fr'?catFr[c]:c}</option>)}</select><input value={form.emoji} onChange={e=>set('emoji',e.target.value)} placeholder="🍕"/><button className="save"><Save/> {t.saveChanges}</button></form></div>}
}
createRoot(document.getElementById('root')).render(<App/>);
